models:
  - type: main
    engine: openai
    model: qwen/qwen3.8-27b
    parameters:
      base_url: "https://api.groq.com/openai/v1"

  - type: embeddings
    engine: SentenceTransformers
    model: NeuML/bioclinical-modernbert-base-embeddings

rails:
  dialog:
    user_messages:
      embeddings_only: True
      embeddings_only_similarity_threshold: 0.6